import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
import os

MAIL_USERNAME = 'nonzwork11@gmail.com'
MAIL_PASSWORD = 'qhkt tovk nxqg irhe'
RECEIVER_EMAIL = 'nonzwork11@gmail.com'

def send_intruder_alert(image_path: str, intruder_name: str = "Unknown"):
    msg = MIMEMultipart()
    msg['From'] = MAIL_USERNAME
    msg['To'] = RECEIVER_EMAIL
    msg['Subject'] = "Access Request"

    html = f"""
    <html>
      <body style="font-family: Arial, sans-serif;">
        <div style="max-width: 600px; margin: auto; background-color: #fff; padding: 20px; border-radius: 10px;">
          <h2 style="color: red;">🚨 Unauthorized Access Attempt</h2>
          <p><strong>Intruder:</strong> {intruder_name}</p>
          <img src="cid:intruder_image" style="width: 300px; border-radius: 10px;" />
          <p style="margin-top: 20px;">Reply to this email with:</p>
          <ul>
            <li><b>approve</b> — to grant access</li>
            <li><b>deny</b> — to keep the system locked</li>
          </ul>
          <p style="font-size: 12px; color: #999;">This alert was generated by your system.</p>
        </div>
      </body>
    </html>
    """

    msg.attach(MIMEText(html, 'html'))

    if os.path.exists(image_path):
        with open(image_path, 'rb') as img_file:
            image = MIMEImage(img_file.read())
            image.add_header('Content-ID', '<intruder_image>')
            msg.attach(image)

    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(MAIL_USERNAME, MAIL_PASSWORD)
        server.sendmail(MAIL_USERNAME, RECEIVER_EMAIL, msg.as_string())
        server.quit()
        print("✅ Email sent!")
    except Exception as e:
        print("❌ Email failed:", e)
